# Generated by Django 4.2.1 on 2023-05-24 04:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_prefered_complete_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(help_text='Comment about the order or user.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the feedback was created.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(help_text='Order that the feedback is related to.', on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(help_text='Rating from 1 (worst) to 5 (best).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reviewed',
            field=models.ForeignKey(default=3, help_text='User that the feedback is about.', on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_feedbacks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reviewer',
            field=models.ForeignKey(default=2, help_text='User providing the feedback.', on_delete=django.db.models.deletion.PROTECT, related_name='reviewer_feedbacks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
