# Generated by Django 4.2.1 on 2023-06-04 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0002_alter_feedback_comment_alter_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(help_text='Comments about the order or user.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reviewed',
            field=models.ForeignKey(help_text='User that the feedback is about.', on_delete=django.db.models.deletion.PROTECT, related_name='feedback_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reviewer',
            field=models.ForeignKey(help_text='User providing the feedback.', on_delete=django.db.models.deletion.PROTECT, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
