# Generated by Django 4.2.1 on 2023-06-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ['name'], 'verbose_name': 'User type', 'verbose_name_plural': 'User types'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='users_type', to='accounts.usertype'),
        ),
    ]
