# Generated by Django 4.2.1 on 2023-05-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedback_count',
            field=models.IntegerField(default=0),
        ),
    ]
