# Generated by Django 4.2.1 on 2023-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_additional_info_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='client_price',
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
