# Generated by Django 4.2.1 on 2023-05-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_price_order_client_price_order_vendor_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_difficulties', to='orders.orderdifficulty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_status', to='orders.orderstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_types', to='orders.ordertype'),
            preserve_default=False,
        ),
    ]
