# Generated by Django 4.2.1 on 2023-05-22 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_difficulty_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdifficulty',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='order_status', to='orders.orderstatus'),
        ),
    ]
