# Generated by Django 4.2.1 on 2023-05-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderdifficulty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prefered_complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
