# Generated by Django 4.2.1 on 2023-05-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_prefered_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_info',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='special_requests',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
