# Generated by Django 4.2.1 on 2023-06-04 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_alter_order_additional_info_alter_order_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated_date', '-created_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderdifficulty',
            options={'ordering': ['pk'], 'verbose_name': 'Order difficulty', 'verbose_name_plural': 'Order difficulties'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['pk'], 'verbose_name': 'Order status', 'verbose_name_plural': 'Order statuses'},
        ),
        migrations.AlterModelOptions(
            name='ordertype',
            options={'ordering': ['name'], 'verbose_name': 'Order type', 'verbose_name_plural': 'Order types'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='order_difficulty',
            field=models.ForeignKey(default=1, help_text='The difficulty level of the order', on_delete=django.db.models.deletion.PROTECT, related_name='order_difficulties', to='orders.orderdifficulty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=10, help_text='The current status of the order', on_delete=django.db.models.deletion.PROTECT, related_name='order_status', to='orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(default=1, help_text='The type of the order', on_delete=django.db.models.deletion.PROTECT, related_name='order_types', to='orders.ordertype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_info',
            field=models.TextField(blank=True, default='None', help_text='Any additional information from the client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(help_text='The address where the order will be delivered or performed', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(help_text='The user who created the order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_price',
            field=models.DecimalField(decimal_places=2, help_text='The price that the client is willing to pay', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(help_text='The description of the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, help_text='The location of the order', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(help_text='The name of the order', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='prefered_complete_date',
            field=models.DateTimeField(blank=True, help_text='The preferred date for completing the order', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_requests',
            field=models.TextField(blank=True, default='None', help_text='Any special requests from the client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='The user who accepted the order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor_price',
            field=models.DecimalField(decimal_places=2, help_text='The price that the vendor is asking for', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='orderdifficulty',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Order difficulty'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Order type'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='The url of the picture', max_length=255)),
                ('description', models.CharField(blank=True, help_text='The name or description of the picture', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='The order that the picture belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='orders.order')),
                ('user', models.ForeignKey(help_text='The user who uploaded the picture', on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'ordering': ['-created_date'],
            },
        ),
    ]
