# Generated by Django 4.2.1 on 2023-06-05 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_options_alter_orderdifficulty_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_difficulty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AddField(
            model_name='order',
            name='difficulty',
            field=models.ForeignKey(default=1, help_text='The difficulty level of the order', on_delete=django.db.models.deletion.PROTECT, related_name='difficulties', to='orders.orderdifficulty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=10, help_text='The current status of the order', on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.ForeignKey(default=1, help_text='The type of the order', on_delete=django.db.models.deletion.PROTECT, related_name='types', to='orders.ordertype'),
            preserve_default=False,
        ),
    ]
