# Generated by Django 4.2.1 on 2023-06-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_order_name_order_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prefered_complete_date',
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_complete_date',
            field=models.DateTimeField(blank=True, help_text='The preferred date for the order to be completed by', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional information about the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Any special requests from the client'),
        ),
    ]
